[loggers]
keys=root,vayuguard-ml,models,feature_pipeline,inference,monitoring

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=simpleFormatter,detailedFormatter

[logger_root]
level=WARNING
handlers=consoleHandler

[logger_vayuguard-ml]
level=INFO
handlers=consoleHandler,fileHandler
qualname=vayuguard-ml
propagate=0

[logger_models]
level=INFO
handlers=consoleHandler,fileHandler
qualname=models
propagate=0

[logger_feature_pipeline]
level=INFO
handlers=consoleHandler,fileHandler
qualname=feature_pipeline
propagate=0

[logger_inference]
level=INFO
handlers=consoleHandler,fileHandler
qualname=inference
propagate=0

[logger_monitoring]
level=INFO
handlers=consoleHandler,fileHandler
qualname=monitoring
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=simpleFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=handlers.RotatingFileHandler
level=DEBUG
formatter=detailedFormatter
args=('./logs/vayuguard-ml.log', 'a', 10485760, 5)

[formatter_simpleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=%Y-%m-%d %H:%M:%S

[formatter_detailedFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s
datefmt=%Y-%m-%d %H:%M:%S
