apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  labels:
    app: ml-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ml-service

  template:
    metadata:
      labels:
        app: ml-service

    spec:
      containers:
      - name: ml-service
        image: adithyaganesh640/ml-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000