apiVersion: v1
kind: Secret
metadata:
  name: placemux-secrets
type: Opaque
stringData:
  JWT_SECRET: placemux-super-secret-key-2024
  MONGO_URI: mongodb://mongo:27017/placemux
  POSTGRES_PASSWORD: PlaceMux@123
  REDIS_URL: redis://redis:6379